name: Mirroring

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2028/B-DOP-200-LIL-2-1-bschocolatine-helene.houplain.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}